Repository Habbo420/student-time-sceduler-app, pull requests merged in 2022-05, with the labels that each got.

#14 Added adding event scene
  SchedulingApp/src/main/java/com/example/schedulingapp/HelloApplication.java
Labels: Developing

#18 Delete TimeTableScene.java the old one
  TimeTableScene.java
Labels: duplicate

#23 Added commented out code for main java file
  SchedulingApp/src/main/java/com/example/schedulingapp/HelloApplication.java
Labels: enhancement

#22 Adding java class for the addign event scene
  SchedulingApp/src/main/java/com/example/schedulingapp/AddingEvent.java
Labels: Developing

#35 Add files via upload
  SchedulingApp/src/main/java/com/example/schedulingapp/TimeTableGui.java
  SchedulingApp/src/main/java/com/example/schedulingapp/studentDetailsTimeTable.java
Labels: Developing
